### ISSUE TITLE
Adding MeqSilhouette

### ISSUE THREAD

**Issue by iniyannatarajan** [ptiede/ngEHT2021-Tutorial#1]
Hi Paul,

Can you add MeqSilhouette to the list of synthetic data generation packages?

You can use the following links -- [https://meqsilhouette.readthedocs.io](https://meqsilhouette.readthedocs.io) and [https://github.com/rdeane/MeqSilhouette/](https://github.com/rdeane/MeqSilhouette/)

**Comment by ptiede** [comment]
Done!
